/**
 ******************************************************************************
 * @file    mx.c
 * @author  STMicroelectronics - AIS - MCD Team
 * @version 1.0.0
 * @date    Apr 9, 2021
 *
 * @brief Project peripherals configuration files.
 *
 * This files defines the peripherals configuration parameters that can be used
 * in the Low Level API of an eLooM driver - IDrvInit(). It creates a link
 * between the initialization code generated by CubeMX (see the .ioc file
 * in the tools folder) and the eLooM framework.
 *
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2021 STMicroelectronics
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  ******************************************************************************
 */

#include "mx.h"
#include "spi.h"
#include "i2c.h"
#include "dfsdm.h"
#include "adc.h"
#include "dma.h"
#include "usart.h"
#include "tim.h"
#include "gpio.h"

/**
 * SPI3 initialization parameters.
 */
const MX_SPIParams_t MX_SPI3InitParams = {
    .p_mx_init_f = MX_SPI3_Init,
    .p_spi_handle  = &hspi3,
    .p_mx_dma_init_f = MX_DMA_InitCustom,
    .spi_dma_rx_irq_n = DMA1_Channel1_IRQn,
    .spi_dma_tx_irq_n = DMA1_Channel2_IRQn
};

/**
 * SPI2 initialization parameters.
 */
const MX_SPIParams_t MX_SPI2InitParams = {
    .p_mx_init_f = MX_SPI2_Init,
    .p_spi_handle = &hspi2,
    .p_mx_dma_init_f = NULL, /*!< NOT USED */
    .spi_dma_rx_irq_n = UsageFault_IRQn, /*!< NOT USED */
    .spi_dma_tx_irq_n = UsageFault_IRQn /*!< NOT USED */
};

/**
 * I2C2 initialization parameters.
 */
const MX_I2CParams_t MX_I2C2InitParams = {
    .p_mx_init_f = MX_I2C2_Init,
    .p_i2c_handle = &hi2c2,
    .p_mx_dma_init_f = MX_DMA_InitCustom,
    .i2c_er_irq_n = I2C2_ER_IRQn,
    .i2c_ev_irq_n = I2C2_EV_IRQn,
    .i2c_dma_rx_irq_n = DMA1_Channel3_IRQn,
    .i2c_dma_tx_irq_n = DMA1_Channel4_IRQn
};

/**
 * DFSDM initialization parameters.
 */
const MX_DFSDMParams_t MX_DFSDMCH0F1InitParams = {
    .p_dfsdm_channel = &hdfsdm1_channel0,
    .p_dfsdm_filter = &hdfsdm1_filter1,
    .irq_n = DMA1_Channel6_IRQn,
    .p_mx_init_f = MX_DFSDM1_Init,
    .p_mx_dma_init_f = MX_DMA_InitCustom
};

/**
 * ADC1 initialization parameters.
 */
const MX_ADCParams_t MX_ADC1InitParams = {
    .p_adc = &hadc1,
    .p_mx_init_f = MX_ADC1_Init
};

/**
 * TIM5 initialization parameters.
 */
const MX_TIMParams_t MX_TIM5InitParams = {
    .p_mx_init_f = MX_TIM5_Init,
    .p_tim = &htim5,
    .irq_n = TIM5_IRQn
};

/**
 * TIM16 initialization parameters.
 */
const MX_TIMParams_t MX_TIM16InitParams = {
    .p_mx_init_f = MX_TIM16_Init,
    .p_tim = &htim16,
    .irq_n = TIM1_UP_TIM16_IRQn
};

/**
 * PF6 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PF6InitParams = {
    MX_GPIO_PF6_Init,
    UsageFault_IRQn, /*!< NOT USED */
    GPIO_PIN_6,
    GPIOF
};
